# Site settings
title: InsertLearning
email: support@insertlearning.com
description: > # this means to ignore newlines until "baseurl:"
  Insert instructional content into any web page
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://insertlearning.com" # the base hostname & protocol for your site
twitter_username: InsertLearning
github_username:  InsertLearning
permalink: /blog/:year/:month/:day/:title.html
image: og.png

# Build settings
markdown: kramdown
