# Site settings
title: DocentEDU
email: support@docentedu.com
description: > # this means to ignore newlines until "baseurl:"
  Turn any online text into an interactive, engaging, and rich learning experience with only a few clicks.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://docentedu.com:3000" # the base hostname & protocol for your site
twitter_username: DocentEDU
github_username:  jekyll
permalink: /blog/:year/:month/:day/:title.html

# Build settings
markdown: kramdown
